### ISSUE TITLE
When deploying, various errors occur, but the contract is created.

### ISSUE THREAD

**Issue by Kosrotoff** [NFT-Meetup-Example/smart-contracts#1]
Hangs on zero block:
```
1_initial_migration.js
======================

   Replacing 'Migrations'
   ----------------------
   > transaction hash:    0x940623fa78e00755b639a6a73c1cfcbfaafa8db1f5492dce0c35f5e958b56a28
   ⠏ Blocks: 0            Seconds: 614
```

**Comment by deadblackclover** [comment]
@Kosrotoff Can we have a full log of where the errors are.

**Comment by Kosrotoff** [comment]
Now I tried to deploy again and here is the new result.

Before launching the deployment, I made changes in the code:
In the NFT.sol file:
``require(_totalSupply < 10000, "NFTs are out of stock!");`` to ``require(_totalSupply < 2, "NFTs are out of stock!");``
And changed the name of ``Non-fungible_token`` to ``MyNFT`` in all files.

Result "npm run deploy:mumbai":
```
> smart-contracts@1.0.0 deploy:mumbai
> truffle deploy --network mumbai --reset


Compiling your contracts...
===========================
√ Fetching solc version list from solc-bin. Attempt #1
√ Fetching solc version list from solc-bin. Attempt #1
> Compiling @openzeppelin\contracts\access\Ownable.sol
> Compiling @openzeppelin\contracts\token\ERC721\ERC721.sol
> Compiling @openzeppelin\contracts\token\ERC721\IERC721.sol
> Compiling @openzeppelin\contracts\token\ERC721\IERC721Receiver.sol
> Compiling @openzeppelin\contracts\token\ERC721\extensions\IERC721Metadata.sol
> Compiling @openzeppelin\contracts\utils\Address.sol
> Compiling @openzeppelin\contracts\utils\Context.sol
> Compiling @openzeppelin\contracts\utils\Strings.sol
> Compiling @openzeppelin\contracts\utils\introspection\ERC165.sol
> Compiling @openzeppelin\contracts\utils\introspection\IERC165.sol
> Compiling .\contracts\Migrations.sol
> Compiling .\contracts\NFT.sol
> Artifacts written to W:\projects\smart-contracts\build\contracts
> Compiled successfully using:
   - solc: 0.8.15+commit.e14f2714.Emscripten.clang


Starting migrations...
======================
> Network name:    'mumbai'
> Network id:      80001
> Block gas limit: 19765915 (0x12d9a9b)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
   > transaction hash:    0xe46278b39e39cce0cdf5df9d02bfb987d2bb926049ab8557126d2dada089bcbd
   > Blocks: 19           Seconds: 41
   > contract address:    0x28bBB7dA6fb08BB75aE002D75e3A11078810F7c1
   > block number:        26830923
   > block timestamp:     1655735571
   > account:             0x48e98Bb8673C80a145734894C35f1e3f53a90616
   > balance:             1.197241942484828711
   > gas used:            176252 (0x2b07c)
   > gas price:           2.500000009 gwei
   > value sent:          0 ETH
   > total cost:          0.000440630001586268 ETH

   Pausing for 2 confirmations...

   -------------------------------
   > confirmation number: 2 (block: 26830925)
   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:     0.000440630001586268 ETH


2_deploy_contracts.js
=====================

   Deploying 'NFT'
   ---------------
   > transaction hash:    0x543eae868845be9f3cb5578f7a8448ce58ca6edab907737f53cd8665e8709fd4
null Blocks: -2311        Seconds: 12

W:\projects\smart-contracts\node_modules\web3-provider-engine\index.js:160
        cb(null, null)
        ^
Error: Could not find block
    at W:\projects\smart-contracts\node_modules\web3-provider-engine\index.js:59:28
    at afterRequest (W:\projects\smart-contracts\node_modules\web3-provider-engine\index.js:160:9)
    at W:\projects\smart-contracts\node_modules\web3-provider-engine\index.js:175:12
    at W:\projects\smart-contracts\node_modules\web3-provider-engine\index.js:234:9
    at W:\projects\smart-contracts\node_modules\async\internal\once.js:12:16
    at replenish (W:\projects\smart-contracts\node_modules\async\internal\eachOfLimit.js:61:25)
    at W:\projects\smart-contracts\node_modules\async\internal\eachOfLimit.js:71:9
    at eachLimit (W:\projects\smart-contracts\node_modules\async\eachLimit.js:43:36)
    at W:\projects\smart-contracts\node_modules\async\internal\doLimit.js:9:16
    at end (W:\projects\smart-contracts\node_modules\web3-provider-engine\index.js:211:5)
    at Request._callback (W:\projects\smart-contracts\node_modules\web3-provider-engine\subproviders\rpc.js:72:5)
    at Request.self.callback (W:\projects\smart-contracts\node_modules\request\request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (W:\projects\smart-contracts\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (W:\projects\smart-contracts\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

```

**Comment by deadblackclover** [comment]
The standard RPC Endpoints provided by Polygon itself are used for deployment. They may not always work stably.

https://docs.polygon.technology/docs/develop/network-details/network/

Here you can find alternative services which also provide RPC Endpoint.

**Comment by Kosrotoff** [comment]
I tried again - it worked! Thank you!
